[package]
name = "budget-app"
version = "0.1.0"
authors = ["esty"]

[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
